// Protocol Buffers - Google's data interchange format
// Copyright 2026 Google LLC.  All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file or at
// https://developers.google.com/open-source/licenses/bsd

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/protobuf/json_enumvalue_options.proto

package jsonenumvalueoptionspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

type JsonEnumValueOptions struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_String_     *string                `protobuf:"bytes,1,opt,name=string"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *JsonEnumValueOptions) Reset() {
	*x = JsonEnumValueOptions{}
	mi := &file_google_protobuf_json_enumvalue_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonEnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonEnumValueOptions) ProtoMessage() {}

func (x *JsonEnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_google_protobuf_json_enumvalue_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JsonEnumValueOptions) GetString() string {
	if x != nil {
		if x.xxx_hidden_String_ != nil {
			return *x.xxx_hidden_String_
		}
		return ""
	}
	return ""
}

func (x *JsonEnumValueOptions) SetString(v string) {
	x.xxx_hidden_String_ = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *JsonEnumValueOptions) HasString() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *JsonEnumValueOptions) ClearString() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_String_ = nil
}

type JsonEnumValueOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Allows user to specify a custom string to use when serializing an enum
	// value to JSON.
	//
	// Sample usage:
	//
	//	enum Foo {
	//	  ...
	//	  FOO_BAR = 42 [(pb.enumvalue.json).string = "my_custom_name"];
	//	}
	String *string
}

func (b0 JsonEnumValueOptions_builder) Build() *JsonEnumValueOptions {
	m0 := &JsonEnumValueOptions{}
	b, x := &b0, m0
	_, _ = b, x
	if b.String != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_String_ = b.String
	}
	return m0
}

var file_google_protobuf_json_enumvalue_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*JsonEnumValueOptions)(nil),
		Field:         998,
		Name:          "pb.enumvalue.json",
		Tag:           "bytes,998,opt,name=json",
		Filename:      "google/protobuf/json_enumvalue_options.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional pb.enumvalue.JsonEnumValueOptions json = 998;
	E_Json = &file_google_protobuf_json_enumvalue_options_proto_extTypes[0]
)

var File_google_protobuf_json_enumvalue_options_proto protoreflect.FileDescriptor

const file_google_protobuf_json_enumvalue_options_proto_rawDesc = "" +
	"\n" +
	",google/protobuf/json_enumvalue_options.proto\x12\fpb.enumvalue\x1a google/protobuf/descriptor.proto\"0\n" +
	"\x14JsonEnumValueOptions\x12\x16\n" +
	"\x06string\x18\x01 \x01(\tR\x06stringX\x01:b\n" +
	"\x04json\x12!.google.protobuf.EnumValueOptions\x18\xe6\a \x01(\v2\".pb.enumvalue.JsonEnumValueOptionsB\x06\xb2\x01\x03\b\xea\aR\x04jsonB\x1a\n" +
	"\x18com.google.protobuf.utilb\beditionsp\xe9\a"

var file_google_protobuf_json_enumvalue_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_protobuf_json_enumvalue_options_proto_goTypes = []any{
	(*JsonEnumValueOptions)(nil),          // 0: pb.enumvalue.JsonEnumValueOptions
	(*descriptorpb.EnumValueOptions)(nil), // 1: google.protobuf.EnumValueOptions
}
var file_google_protobuf_json_enumvalue_options_proto_depIdxs = []int32{
	1, // 0: pb.enumvalue.json:extendee -> google.protobuf.EnumValueOptions
	0, // 1: pb.enumvalue.json:type_name -> pb.enumvalue.JsonEnumValueOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_protobuf_json_enumvalue_options_proto_init() }
func file_google_protobuf_json_enumvalue_options_proto_init() {
	if File_google_protobuf_json_enumvalue_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_protobuf_json_enumvalue_options_proto_rawDesc), len(file_google_protobuf_json_enumvalue_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_google_protobuf_json_enumvalue_options_proto_goTypes,
		DependencyIndexes: file_google_protobuf_json_enumvalue_options_proto_depIdxs,
		MessageInfos:      file_google_protobuf_json_enumvalue_options_proto_msgTypes,
		ExtensionInfos:    file_google_protobuf_json_enumvalue_options_proto_extTypes,
	}.Build()
	File_google_protobuf_json_enumvalue_options_proto = out.File
	file_google_protobuf_json_enumvalue_options_proto_goTypes = nil
	file_google_protobuf_json_enumvalue_options_proto_depIdxs = nil
}
